Xray introbox
ua-snap/ardac-explorer pull request #182
Opened 2024-12-05 04:21 UTC by brucecrevensten

testing:
- elevation is a non-climate xray introblurb
- cmip5 and cmip6 show different example models/scenario examples!
- hydrology + degree days are restored in this branch
- text is not as wide

2024-12-13 01:23 UTC, MikeDelue commented
Question: The Historical Sea Ice extent blurb includes the "no peer reviewed publication" blurb but [does have a publication attached](https://www.tandfonline.com/doi/full/10.1111/j.1931-0846.2016.12195.x). Is this intended? Otherwise I don't see any issues.

2024-12-13 01:26 UTC, MikeDelue requested changes
Several blurbs include "No peer reviewed pub" in this implementation which I think should not: /alfresco-flammability or /sea-ice-concentration as examples. Some of the CMIP6 datasets also seem to reference Mizukami et. al. in spite of (I think) still being pre-publication?

2024-12-14 01:49 UTC, cstephen requested changes
This all looks good to me, but it looks like we also need to:

- Enable the Precipitation Frequency item by uncommenting it in `items.ts` and `slugs.d.ts`.
- I think we want to add a link for "Hydrology" back to `Tagbar.vue`. I don't think the Hydrology items are discoverable otherwise since they are each tagged with only the `Hydrology` tag and don't appear on any other pages.

2025-01-14 22:34 UTC, BobTorgerson approved these changes
This all looks good to me! I'm definitely going to use the map layer element for loops in my most recent items too.

2025-01-14 22:35 UTC, merged